

services:
  supabase:
    image: supabase/postgres:15.2.0
    container_name: service-tool-supabase
    volumes:
      - ./supabase/migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always
  backend:
    image: ${DOCKERHUB_USERNAME}/service-tool-backend:${IMAGE_TAG}
    container_name: service-tool-backend
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    restart: always

  frontend:
    image: ${DOCKERHUB_USERNAME}/service-tool-frontend:${IMAGE_TAG}
    container_name: service-tool-frontend
    ports:
      - "80:80"
    restart: always
