name: Deploy Service Tool

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: [self-hosted]
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3



      # Define image names as outputs
      - name: Set Docker image names
        id: set-image-names
        run: |
          echo "backend_image=service-tool-backend:${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT
          echo "frontend_image=service-tool-frontend:${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT

      # Build backend image
      - name: Build backend image
        run: |
          docker build \
            --file backend/Dockerfile \
            --tag ${{ steps.set-image-names.outputs.backend_image }} \
            .

      # Build frontend image
      - name: Build frontend image
        run: |
          docker build \
            --file Dockerfile.frontend \
            --tag ${{ steps.set-image-names.outputs.frontend_image }} \
            .


      # Deploy with docker-compose
      - name: Deploy stack with docker-compose
        run: |
          docker-compose pull
          docker-compose up -d

      # Health check backend
      - name: Health check backend
        run: |
          sleep 10
          curl -f http://localhost/api/ || (echo "Backend health check failed" && exit 1)

      # Health check frontend
      - name: Health check frontend
        run: |
          sleep 10
          curl -f http://localhost/ || (echo "Frontend health check failed" && exit 1)

      # Setup Node.js for GitHub Pages deployment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      # Install dependencies
      - name: Install dependencies
        run: npm ci
        
      # Build for GitHub Pages
      - name: Build for GitHub Pages
        run: npm run build
          
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
