name: Deploy Service Tool

on:
  push:
    branches:
      - production

env:
  IMAGE_TAG: ${{ github.sha }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: |
          docker build \
            --file backend/Dockerfile \
            --tag $DOCKERHUB_USERNAME/service-tool-backend:$IMAGE_TAG \
            .

      - name: Build frontend image
        run: |
          docker build \
            --file Dockerfile.frontend \
            --tag $DOCKERHUB_USERNAME/service-tool-frontend:$IMAGE_TAG \
            .

      - name: Push backend image
        run: docker push $DOCKERHUB_USERNAME/service-tool-backend:$IMAGE_TAG

      - name: Push frontend image
        run: docker push $DOCKERHUB_USERNAME/service-tool-frontend:$IMAGE_TAG

      - name: Deploy stack with docker-compose
        run: |
          docker-compose pull
          docker-compose up -d
